source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '13.0'

target 'FDGroupAvatarView_Example' do
  pod 'FDGroupAvatarView', :path => '../'

  target 'FDGroupAvatarView_Tests' do
    inherit! :search_paths

    
  end
end
